"""Initial migration

Revision ID: feb3d3d593e7
Revises: 
Create Date: 2025-11-29 00:20:22.272768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'feb3d3d593e7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donor_partners',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('GOVERNMENT', 'RELIGIOUS', 'NON_PROFIT', 'FAMILY_OFFICE', 'INDIVIDUAL', 'BUSINESS', 'UNIVERSITY', name='donorcategory'), nullable=False),
    sa.Column('tier', sa.Enum('PLATINUM', 'GOLD', 'SILVER', 'BRONZE', 'COMMUNITY', name='donortier'), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('total_contribution_display', sa.String(), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.Column('anonymous_name', sa.String(), nullable=True),
    sa.Column('quote', sa.Text(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('since', sa.String(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donor_partners_id'), 'donor_partners', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('GUEST', 'SEEKER', 'DONOR', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('avatar_id', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('zip', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('radius', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('verification_status', sa.Enum('UNVERIFIED', 'PENDING', 'VERIFIED', name='verificationstatus'), nullable=True),
    sa.Column('verification_steps', sa.JSON(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('languages', sa.JSON(), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.Column('weekly_meal_limit', sa.Integer(), nullable=True),
    sa.Column('current_weekly_meals', sa.Integer(), nullable=True),
    sa.Column('donor_category', sa.Enum('GOVERNMENT', 'RELIGIOUS', 'NON_PROFIT', 'FAMILY_OFFICE', 'INDIVIDUAL', 'BUSINESS', 'UNIVERSITY', name='donorcategory'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('flagged_content',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('flagged_by', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('dismissed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['flagged_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flagged_content_id'), 'flagged_content', ['id'], unique=False)
    op.create_table('meal_offers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('donor_id', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('zip', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('dietary_tags', sa.JSON(), nullable=False),
    sa.Column('medical_tags', sa.JSON(), nullable=True),
    sa.Column('available_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('logistics', sa.JSON(), nullable=False),
    sa.Column('availability', sa.String(), nullable=False),
    sa.Column('frequency', sa.Enum('ONCE', 'WEEKLY', 'DAILY', 'AS_NEEDED', name='frequency'), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'IN_PROGRESS', 'CLAIMED', 'FLAGGED', name='offerstatus'), nullable=False),
    sa.Column('completion_pin', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_offers_id'), 'meal_offers', ['id'], unique=False)
    op.create_table('meal_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('seeker_id', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('zip', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('dietary_needs', sa.JSON(), nullable=False),
    sa.Column('medical_needs', sa.JSON(), nullable=False),
    sa.Column('logistics', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('availability', sa.String(), nullable=False),
    sa.Column('frequency', sa.Enum('ONCE', 'WEEKLY', 'DAILY', 'AS_NEEDED', name='frequency'), nullable=False),
    sa.Column('urgency', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'FULFILLED', 'PAUSED', 'EXPIRED', 'FLAGGED', name='requeststatus'), nullable=False),
    sa.Column('completion_pin', sa.String(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['seeker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_requests_id'), 'meal_requests', ['id'], unique=False)
    op.create_table('ratings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('from_user_id', sa.String(), nullable=False),
    sa.Column('to_user_id', sa.String(), nullable=False),
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratings_id'), 'ratings', ['id'], unique=False)
    op.create_table('chat_threads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('offer_id', sa.String(), nullable=True),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('student_id', sa.String(), nullable=False),
    sa.Column('donor_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['meal_offers.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['meal_requests.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_threads_id'), 'chat_threads', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('sender_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('offer_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['meal_offers.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['meal_requests.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['chat_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_chat_threads_id'), table_name='chat_threads')
    op.drop_table('chat_threads')
    op.drop_index(op.f('ix_ratings_id'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_meal_requests_id'), table_name='meal_requests')
    op.drop_table('meal_requests')
    op.drop_index(op.f('ix_meal_offers_id'), table_name='meal_offers')
    op.drop_table('meal_offers')
    op.drop_index(op.f('ix_flagged_content_id'), table_name='flagged_content')
    op.drop_table('flagged_content')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_donor_partners_id'), table_name='donor_partners')
    op.drop_table('donor_partners')
    # ### end Alembic commands ###
